name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Sesuaikan dengan versi PHP yang Anda gunakan

      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-interaction

      - name: Run PHP tests (jika ada)
        run: |
          # Jika Anda memiliki unit tests, jalankan dengan perintah ini:
          vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Pastikan langkah deploy hanya berjalan setelah build selesai
    if: github.ref == 'refs/heads/main'  # Deploy hanya jika commit ada di branch 'main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          echo "Deploying to server"
          # Tambahkan perintah deployment Anda di sini (misalnya SSH ke server untuk melakukan deploy)
          # ssh user@server "deploy script"
